import { notFound } from "next/navigation";
import { EvaluationLayout, evaluationDate } from "@/components/evaluations/EvaluationLayout";
import { AnswerSummary } from "@/components/evaluations/AnswerSummary";
import { ManagementForm } from "@/components/evaluations/ManagementForm";
import { addEvaluationFeedback, changeCampaignWindow, reopenEvaluation } from "@/app/avaliacoes/actions";
import { evaluationPageContext } from "@/lib/evaluations/server";
import { evaluationLocalDate, isUuid, PROGRAM_RATINGS } from "@/lib/evaluations/rules";
import type { EvaluationCampaign, EvaluationFeedback, EvaluationResponse } from "@/types/evaluations";

export default async function ManageEvaluationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!isUuid(id)) notFound();
  const { supabase, manager } = await evaluationPageContext("reviewer");
  const { data, error } = await supabase.from("evaluation_campaigns").select("*").eq("id", id).maybeSingle();
  if (error) throw new Error("Não foi possível carregar a avaliação.");
  if (!data) notFound();
  const campaign = data as EvaluationCampaign;
  // A professor may see a campaign as a participant, so separately enforce reviewer scope.
  const { data: allowed, error: permissionError } = await supabase.rpc(campaign.kind === "self" ? "get_evaluation_roster" : "get_program_evaluation_summary", { p_campaign_id: id });
  if (permissionError) notFound();
  const roster = campaign.kind === "self" ? (allowed ?? []) as { profile_id: string; full_name: string; status: string }[] : [];
  const summary = campaign.kind === "program" ? allowed as { available: boolean; response_count?: number; ratings?: Record<string, { count: number; average: number } | null> } : null;
  const responsesResult = campaign.kind === "self" ? await supabase.from("evaluation_responses").select("*").eq("campaign_id", id).eq("status", "submitted").order("submitted_at", { ascending: false }) : { data: [], error: null };
  if (responsesResult.error) throw new Error("Não foi possível carregar os envios.");
  const responses = (responsesResult.data ?? []) as EvaluationResponse[];
  const feedbackResult = responses.length ? await supabase.from("evaluation_feedback").select("*").in("response_id", responses.map((item) => item.id)).order("created_at") : { data: [], error: null };
  if (feedbackResult.error) throw new Error("Não foi possível carregar as devolutivas.");
  const feedback = (feedbackResult.data ?? []) as EvaluationFeedback[];
  const submitted = roster.filter((item) => item.status === "submitted").length;
  const percent = roster.length ? Math.round(100 * submitted / roster.length) : 0;
  return <EvaluationLayout title={campaign.title} description={`${campaign.kind === "self" ? "Avaliação identificada do curso" : "Resultados anônimos do programa"}. Período: ${evaluationDate(campaign.opens_at)} a ${evaluationDate(campaign.closes_at)}.`} back="/gestao-avaliacoes" backLabel="Gestão de avaliações">
    {manager && <details className="rounded-lg border border-stone-200 bg-white p-5"><summary className="cursor-pointer font-semibold">Gerenciar período da avaliação</summary><div className="mt-5 grid gap-6 sm:grid-cols-2">
      {!(campaign.kind === "program" && campaign.status === "closed") && <ManagementForm action={changeCampaignWindow.bind(null, id)} label="Salvar período e abrir"><input type="hidden" name="status" value="open" /><label className="grid gap-2 text-sm">Abertura (Brasília)<input name="opens_at" type="date" required defaultValue={evaluationLocalDate(campaign.opens_at)} className="rounded-md border border-stone-300 p-2" /></label><label className="grid gap-2 text-sm">Encerramento (Brasília)<input name="closes_at" type="date" required defaultValue={evaluationLocalDate(campaign.closes_at)} className="rounded-md border border-stone-300 p-2" /></label></ManagementForm>}
      {campaign.status !== "closed" ? <ManagementForm action={changeCampaignWindow.bind(null, id)} label="Encerrar avaliação"><input type="hidden" name="status" value="closed" /><p className="text-sm leading-6 text-stone-600">Encerrar impede novos envios. {campaign.kind === "program" && "A avaliação anônima encerrada não poderá ser reaberta. Seus resultados serão liberados somente se houver respostas suficientes."}</p><label className="flex gap-2 text-sm"><input type="checkbox" required />Confirmo o encerramento.</label></ManagementForm> : <p className="text-sm text-stone-600">Avaliação encerrada.{campaign.kind === "program" && " Crie uma nova avaliação para o próximo período."}</p>}
    </div></details>}
    {campaign.kind === "program" ? <section className="rounded-lg border border-green-200 bg-green-50 p-6"><h2 className="text-xl font-semibold">Opiniões agrupadas</h2>{!summary?.available ? <p className="mt-4 text-sm leading-6">Os resultados aparecem após o encerramento e com pelo menos cinco respostas. Cada dimensão também precisa de cinco notas válidas. Não se divulga quem respondeu.</p> : <><p className="mt-3 text-sm">{summary.response_count} respostas recebidas. Contagem de envios, sem identificação de pessoas distintas. Não se calcula taxa individual de participação.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(PROGRAM_RATINGS).map(([key, label]) => <div key={key} className="rounded-lg bg-white p-4"><dt className="text-sm text-stone-600">{label}</dt><dd className="mt-2 text-2xl font-semibold text-folha">{summary.ratings?.[key] ? `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(summary.ratings[key]!.average)} / 5` : "Amostra insuficiente"}</dd></div>)}</dl></>}</section> : <>
      <section className="rounded-lg border border-stone-200 bg-white p-6"><h2 className="text-xl font-semibold">Participação na avaliação</h2><p className="mt-3 text-sm">{submitted} de {roster.length} alunos atualmente elegíveis enviaram a avaliação ({percent}%).</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{roster.map((item) => <div key={item.profile_id} className="flex items-center justify-between gap-4 rounded bg-stone-50 p-3 text-sm"><span>{item.full_name}</span><span className="text-xs font-semibold text-folha">{item.status === "submitted" ? "Enviada" : item.status === "draft" ? "Rascunho privado" : "Pendente"}</span></div>)}</div><p className="mt-4 text-xs text-stone-500">O conteúdo dos rascunhos permanece privado. Alterações de matrícula podem mudar a lista de elegíveis; envios anteriores continuam preservados.</p></section>
      <section><h2 className="text-xl font-semibold">Envios e orientações</h2>{!responses.length && <p className="mt-4 text-sm text-stone-600">Nenhum envio concluído disponível.</p>}{responses.map((response) => <details key={response.id} className="mt-4 rounded-lg border border-stone-200 bg-white p-5"><summary className="cursor-pointer font-semibold">{roster.find((item) => item.profile_id === response.profile_id)?.full_name || "Participante com registro histórico"} · {evaluationDate(response.submitted_at!)}</summary><div className="mt-5 space-y-6"><AnswerSummary answers={response.answers} /><div className="border-t border-stone-200 pt-5"><h3 className="mb-4 font-semibold">Devolutiva pedagógica</h3>{feedback.filter((item) => item.response_id === response.id).map((item) => <p key={item.id} className="mb-4 whitespace-pre-wrap break-words border-l-4 border-folha pl-3 text-sm leading-6">{item.message}</p>)}<ManagementForm action={addEvaluationFeedback.bind(null, response.id)} label="Registrar devolutiva" resetOnSuccess><label className="grid gap-2 text-sm">Orientação ao aluno<textarea className="rounded-md border border-stone-300 p-3" name="message" rows={3} required minLength={5} maxLength={3000} /></label></ManagementForm></div>{manager && <details className="border-t border-stone-200 pt-4"><summary className="cursor-pointer text-sm font-semibold">Autorizar correção da resposta</summary><div className="mt-4"><ManagementForm action={reopenEvaluation.bind(null, response.id)} label="Reabrir resposta"><p className="text-xs leading-5 text-stone-500">A campanha deve estar aberta e dentro do prazo. O envio atual será preservado no histórico e o aluno poderá enviar uma correção.</p><label className="grid gap-2 text-sm">Justificativa<textarea className="rounded-md border border-stone-300 p-3" name="reason" rows={2} required minLength={10} maxLength={500} /></label></ManagementForm></div></details>}</div></details>)}</section>
    </>}
  </EvaluationLayout>;
}
